"""SVG renderer.

Turns (Diagram, LayoutResult) → an SVG string with:
  * `<style>` block declaring `:root { --bp-<role>: ... }` so the whole
    diagram can be retheme'd by overriding CSS variables.
  * One `<g id="{node.id}" data-role="..." data-shape="...">` per node,
    so consumers can grab individual elements by id (the whole point of
    this project — Claude's blob SVGs lose this).
  * `<title>` and `<desc>` for accessibility.
  * Group/cluster rects under a separate `<g id="groups">` z-layer.

No external dependencies; everything is hand-rolled string assembly. The
output is plain SVG 1.1, compatible with browsers, Inkscape, and Figma's
SVG import.
"""

from __future__ import annotations

import html
from typing import Iterable

from blueprint_svg.ir import Diagram, Node
from blueprint_svg.layout import EdgePath, LayoutResult, NodeBox

_PADDING = 24  # outer SVG padding (px)
_FONT_STACK = (
    "Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif"
)


def render_svg(diagram: Diagram, layout: LayoutResult) -> str:
    """Render the diagram to an SVG string."""
    diagram.validate_refs()

    width = layout.width + _PADDING * 2
    height = layout.height + _PADDING * 2

    parts: list[str] = []
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'viewBox="0 0 {width:.1f} {height:.1f}" '
        f'width="{width:.1f}" height="{height:.1f}" '
        f'role="img" aria-labelledby="bp-title bp-desc" '
        f'data-blueprint-type="{diagram.type}">'
    )

    parts.append(f'<title id="bp-title">{html.escape(diagram.title or "Diagram")}</title>')
    parts.append(
        f'<desc id="bp-desc">{html.escape(diagram.description or "Generated by blueprint.svg")}</desc>'
    )

    parts.append(_render_style(diagram))
    parts.append(_render_defs())

    # Translate everything by padding once, so layout coords stay clean.
    parts.append(f'<g transform="translate({_PADDING},{_PADDING})">')

    parts.append(_render_groups(diagram, layout))
    parts.append(_render_edges(diagram, layout))
    parts.append(_render_nodes(diagram, layout))

    parts.append("</g>")
    parts.append("</svg>")
    return "\n".join(parts)


# --------------------------------------------------------------------------
# Style / defs
# --------------------------------------------------------------------------

def _render_style(diagram: Diagram) -> str:
    tokens = diagram.theme.tokens
    css_vars = "\n      ".join(f"--bp-{k}: {v};" for k, v in tokens.items())
    return f"""<style><![CDATA[
    :root {{
      {css_vars}
    }}
    .bp-node-bg {{ stroke-width: 1.5; }}
    .bp-node-label {{
      font-family: {_FONT_STACK};
      font-size: 13px;
      fill: var(--bp-fg);
      text-anchor: middle;
      dominant-baseline: middle;
      pointer-events: none;
    }}
    .bp-edge {{
      fill: none;
      stroke: var(--bp-edge);
      stroke-width: 1.5;
    }}
    .bp-edge--dashed {{ stroke-dasharray: 6 4; }}
    .bp-edge--dotted {{ stroke-dasharray: 2 4; }}
    .bp-edge-label {{
      font-family: {_FONT_STACK};
      font-size: 11px;
      fill: var(--bp-fg);
      text-anchor: middle;
    }}
    .bp-group-bg {{
      fill: var(--bp-group-bg);
      stroke: var(--bp-group-stroke);
      stroke-dasharray: 4 4;
    }}
    .bp-group-label {{
      font-family: {_FONT_STACK};
      font-size: 11px;
      font-weight: 600;
      fill: var(--bp-neutral);
    }}
    [data-role="primary"]   .bp-node-bg {{ fill: color-mix(in srgb, var(--bp-primary) 12%, white); stroke: var(--bp-primary); }}
    [data-role="secondary"] .bp-node-bg {{ fill: color-mix(in srgb, var(--bp-secondary) 12%, white); stroke: var(--bp-secondary); }}
    [data-role="accent"]    .bp-node-bg {{ fill: color-mix(in srgb, var(--bp-accent) 14%, white); stroke: var(--bp-accent); }}
    [data-role="danger"]    .bp-node-bg {{ fill: color-mix(in srgb, var(--bp-danger) 12%, white); stroke: var(--bp-danger); }}
    [data-role="muted"]     .bp-node-bg {{ fill: color-mix(in srgb, var(--bp-muted) 12%, white); stroke: var(--bp-muted); }}
    [data-role="neutral"]   .bp-node-bg {{ fill: white; stroke: var(--bp-neutral); }}
  ]]></style>"""


def _render_defs() -> str:
    return """<defs>
    <marker id="bp-arrow" viewBox="0 0 10 10" refX="9" refY="5"
            markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M 0 0 L 10 5 L 0 10 z" fill="var(--bp-edge)"/>
    </marker>
  </defs>"""


# --------------------------------------------------------------------------
# Groups
# --------------------------------------------------------------------------

def _render_groups(diagram: Diagram, layout: LayoutResult) -> str:
    if not diagram.groups:
        return '<g id="groups"></g>'
    parts = ['<g id="groups">']
    for g in diagram.groups:
        boxes = [layout.nodes[m] for m in g.members if m in layout.nodes]
        if not boxes:
            continue
        pad = 16
        x0 = min(b.x - b.w / 2 for b in boxes) - pad
        y0 = min(b.y - b.h / 2 for b in boxes) - pad - 16  # leave space for label
        x1 = max(b.x + b.w / 2 for b in boxes) + pad
        y1 = max(b.y + b.h / 2 for b in boxes) + pad
        parts.append(
            f'<g id="group-{html.escape(g.id)}" data-role="{g.role}">'
            f'<rect class="bp-group-bg" x="{x0:.1f}" y="{y0:.1f}" '
            f'width="{x1 - x0:.1f}" height="{y1 - y0:.1f}" rx="8" ry="8"/>'
            f'<text class="bp-group-label" x="{x0 + 10:.1f}" y="{y0 + 14:.1f}">'
            f'{html.escape(g.label)}</text>'
            f'</g>'
        )
    parts.append("</g>")
    return "\n".join(parts)


# --------------------------------------------------------------------------
# Edges
# --------------------------------------------------------------------------

def _render_edges(diagram: Diagram, layout: LayoutResult) -> str:
    parts = ['<g id="edges">']
    edge_lookup = {(e.source, e.target): e for e in diagram.edges}
    for ep in layout.edges:
        e = edge_lookup.get((ep.source, ep.target))
        if e is None or not ep.points:
            continue
        d = _path_d(ep.points)
        cls = "bp-edge"
        if e.style == "dashed":
            cls += " bp-edge--dashed"
        elif e.style == "dotted":
            cls += " bp-edge--dotted"
        marker_attrs = ""
        if e.arrow == "arrow":
            marker_attrs = ' marker-end="url(#bp-arrow)"'
        elif e.arrow == "both":
            marker_attrs = ' marker-start="url(#bp-arrow)" marker-end="url(#bp-arrow)"'
        edge_id = f"edge-{e.source}-{e.target}"
        parts.append(
            f'<g id="{html.escape(edge_id)}" data-source="{html.escape(e.source)}" '
            f'data-target="{html.escape(e.target)}">'
            f'<path class="{cls}" d="{d}"{marker_attrs}/>'
        )
        if e.label and ep.label_pos:
            lx, ly = ep.label_pos
            parts.append(
                f'<text class="bp-edge-label" x="{lx:.1f}" y="{ly:.1f}">'
                f'{html.escape(e.label)}</text>'
            )
        parts.append("</g>")
    parts.append("</g>")
    return "\n".join(parts)


def _path_d(points: Iterable[tuple[float, float]]) -> str:
    pts = list(points)
    if not pts:
        return ""
    d = [f"M {pts[0][0]:.1f} {pts[0][1]:.1f}"]
    for x, y in pts[1:]:
        d.append(f"L {x:.1f} {y:.1f}")
    return " ".join(d)


# --------------------------------------------------------------------------
# Nodes
# --------------------------------------------------------------------------

def _render_nodes(diagram: Diagram, layout: LayoutResult) -> str:
    parts = ['<g id="nodes">']
    for n in diagram.nodes:
        box = layout.nodes.get(n.id)
        if box is None:
            continue
        parts.append(_render_one_node(n, box))
    parts.append("</g>")
    return "\n".join(parts)


def _render_one_node(n: Node, box: NodeBox) -> str:
    shape_svg = _shape_svg(n, box)
    label_lines = _wrap_label(n.label, max_chars=20)
    line_h = 15
    total_h = line_h * len(label_lines)
    start_y = box.y - total_h / 2 + line_h / 2
    label_parts = []
    for i, line in enumerate(label_lines):
        label_parts.append(
            f'<text class="bp-node-label" x="{box.x:.1f}" y="{start_y + i * line_h:.1f}">'
            f'{html.escape(line)}</text>'
        )
    desc = f'<desc>{html.escape(n.note)}</desc>' if n.note else ""
    return (
        f'<g id="{html.escape(n.id)}" data-role="{n.role}" data-shape="{n.shape}">'
        f'{desc}{shape_svg}{"".join(label_parts)}</g>'
    )


def _shape_svg(n: Node, box: NodeBox) -> str:
    x = box.x - box.w / 2
    y = box.y - box.h / 2
    w, h = box.w, box.h
    cx, cy = box.x, box.y

    if n.shape in ("box",):
        return f'<rect class="bp-node-bg" x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}"/>'
    if n.shape in ("rounded", "entity"):
        return f'<rect class="bp-node-bg" x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="10" ry="10"/>'
    if n.shape == "ellipse":
        return f'<ellipse class="bp-node-bg" cx="{cx:.1f}" cy="{cy:.1f}" rx="{w/2:.1f}" ry="{h/2:.1f}"/>'
    if n.shape == "diamond":
        pts = f"{cx:.1f},{y:.1f} {x + w:.1f},{cy:.1f} {cx:.1f},{y + h:.1f} {x:.1f},{cy:.1f}"
        return f'<polygon class="bp-node-bg" points="{pts}"/>'
    if n.shape == "cylinder":
        ry = min(10, h / 4)
        return (
            f'<g class="bp-node-bg">'
            f'<rect x="{x:.1f}" y="{y + ry:.1f}" width="{w:.1f}" height="{h - 2 * ry:.1f}" '
            f'fill="inherit" stroke="inherit"/>'
            f'<ellipse cx="{cx:.1f}" cy="{y + ry:.1f}" rx="{w/2:.1f}" ry="{ry:.1f}" '
            f'fill="inherit" stroke="inherit"/>'
            f'<ellipse cx="{cx:.1f}" cy="{y + h - ry:.1f}" rx="{w/2:.1f}" ry="{ry:.1f}" '
            f'fill="inherit" stroke="inherit"/>'
            f'</g>'
        )
    if n.shape == "cloud":
        # Cheap "cloud": three overlapping ellipses
        return (
            f'<g class="bp-node-bg">'
            f'<ellipse cx="{cx - w*0.25:.1f}" cy="{cy:.1f}" rx="{w*0.30:.1f}" ry="{h*0.45:.1f}"/>'
            f'<ellipse cx="{cx:.1f}" cy="{cy - h*0.10:.1f}" rx="{w*0.35:.1f}" ry="{h*0.55:.1f}"/>'
            f'<ellipse cx="{cx + w*0.25:.1f}" cy="{cy:.1f}" rx="{w*0.30:.1f}" ry="{h*0.45:.1f}"/>'
            f'</g>'
        )
    if n.shape == "note":
        fold = 14
        pts = (
            f"{x:.1f},{y:.1f} {x + w - fold:.1f},{y:.1f} "
            f"{x + w:.1f},{y + fold:.1f} {x + w:.1f},{y + h:.1f} "
            f"{x:.1f},{y + h:.1f}"
        )
        return f'<polygon class="bp-node-bg" points="{pts}"/>'
    if n.shape == "actor":
        # Stick-figure-ish: circle head + rect body label area
        head_r = min(10, h / 4)
        return (
            f'<g class="bp-node-bg">'
            f'<circle cx="{cx:.1f}" cy="{y + head_r + 2:.1f}" r="{head_r:.1f}"/>'
            f'<rect x="{x:.1f}" y="{y + head_r*2 + 4:.1f}" width="{w:.1f}" '
            f'height="{h - head_r*2 - 4:.1f}" rx="6" ry="6"/>'
            f'</g>'
        )
    if n.shape == "lifeline":
        return f'<rect class="bp-node-bg" x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="4" ry="4"/>'
    if n.shape in ("root", "branch", "leaf"):
        return f'<rect class="bp-node-bg" x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="14" ry="14"/>'
    # Fallback
    return f'<rect class="bp-node-bg" x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}"/>'


def _wrap_label(text: str, max_chars: int) -> list[str]:
    words = text.split()
    if not words:
        return [""]
    lines: list[str] = []
    cur = words[0]
    for w in words[1:]:
        if len(cur) + 1 + len(w) <= max_chars:
            cur += " " + w
        else:
            lines.append(cur)
            cur = w
    lines.append(cur)
    return lines
